language: c
sudo: false

matrix:
  include:
    - os: linux
      env: ICEBALL_CI_TYPE=linux ICEBALL_CI_CMAKE_GENERATOR="Unix Makefiles"
      compiler: gcc
    - os: linux
      env: ICEBALL_CI_TYPE=mingw ICEBALL_CI_CMAKE_GENERATOR="Unix Makefiles" ICEBALL_CI_CMAKE_ARGS="-DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32"
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64

script:
  - cmake --help
  - cmake -DCMAKE_BUILD_TYPE=Release -G "$ICEBALL_CI_CMAKE_GENERATOR" $ICEBALL_CI_CMAKE_ARGS . -Bbuild/
  - cmake --build build/
